name: Promote preprod to prod

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🔁 Copy preprod → prod
        run: |
          cp environments/preprod.yml environments/prod.yml

      - name: 📝 Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add environments/prod.yml
          git commit -m "🚀 Promote preprod to prod"
          git push